default: &default
  adapter: mysql2
  database: rent_app_development
  host: 127.0.0.1
  username: root
  password:
  port: 3306

development:
  <<: *default
  database: rent_app_development

test:
  adapter: sqlite3
  database: db/spree_test.sqlite3
